#!/bin/bash

DIR=/etc/nginx/sites-available
DIR2=/etc/nginx/sites-enabled

echo "domains"

read -p "Domian:" DOMAINS
echo "Куда будет проксировать без http/https"
read -p "Proxy_address:" PROXY
touch $DIR/$DOMAINS.conf
cat << EOF >> $DIR/$DOMAINS.conf
server {
    listen 80;
    server_name $DOMAINS;
    access_log /var/log/nginx/$DOMAINS-access.log;
    error_log /var/log/nginx/$DOMAINS-error.log;
    location / {
        proxy_pass http://$PROXY;
        proxy_set_header Host :$:host;
        proxy_set_header X-Forwarded-For $:proxy_add_x_forwarded_for;
        proxy_set_header X-Real-IP $:remote_addr;
    }
}
EOF

sed -i 's/proxy_set_header Host :$:host;/proxy_set_header Host $host;/g' $DIR/$DOMAINS.conf
sed -i 's/proxy_set_header X-Forwarded-For $:proxy_add_x_forwarded_for;/proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;/g' $DIR/$DOMAINS.conf
sed -i 's/proxy_set_header X-Real-IP $:remote_addr;/proxy_set_header X-Real-IP $remote_addr;/g' $DIR/$DOMAINS.conf

ln -s $DIR/$DOMAINS.conf $DIR2/$DOMAINS.conf
cat /etc/nginx/sites-available/$DOMAINS.conf
echo "test nginx configure"
nginx -t
