#!/bin/bash
#================================
#Name:Create revese-proxy nginx
#Date:08.12.2024
#Autor:h0lik
#Version:0.0.1
#===============================
DIR=/etc/nginx/sites-available
DIR2=/etc/nginx/sites-enabled
check_nginx() {
    if sudo pidof -x nginx > /dev/null
  then
	  echo -e "Nginx............. \e[32m ok!\e[0m"
		exit 0
else
    echo -e "\e[32m Nginx............\e[31m error!\e[0m"
		exit 0
fi
}

reset 
cat << EOF
 ---------------------------------------------------------------------
 #####    #####             ##  ##    ####     ####    ##  ##   ##  ##  
 ##  ##   ##  ##            ### ##   ##  ##     ##     ### ##   ##  ##  
 ##  ##   ##  ##            ######   ##         ##     ######    ####   
 #####    #####    ######   ######   ## ###     ##     ######     ##    
 ####     ##                ## ###   ##  ##     ##     ## ###    ####   
 ## ##    ##                ##  ##   ##  ##     ##     ##  ##   ##  ##  
 ##  ##   ##                ##  ##    ####     ####    ##  ##   ##  ##  
 ---------------------------------------------------------------------
 Create config nginx reverse-proxy
 Domains: domains.com / Your domain name
 Proxy-address: 0.0.0.0:00 / Where are we proxying to
 ---------------------------------------------------------------------
EOF
sleep 2
echo "Enter your domain name"
read -p "Domians:" DOMAINS
echo "Куда будет проксировать без http/https"
read -p "Proxy-address:" PROXY
touch $DIR/$DOMAINS.conf
cat << EOF >> $DIR/$DOMAINS.conf
server {
    listen 80;
    server_name $DOMAINS;
    access_log /var/log/nginx/$DOMAINS-access.log;
    error_log /var/log/nginx/$DOMAINS-error.log;
    location / {
        proxy_pass http://$PROXY;
        proxy_set_header Host :$:host;
        proxy_set_header X-Forwarded-For $:proxy_add_x_forwarded_for;
        proxy_set_header X-Real-IP $:remote_addr;
    }
}
EOF

sed -i 's/proxy_set_header Host :$:host;/proxy_set_header Host $host;/g' $DIR/$DOMAINS.conf
sed -i 's/proxy_set_header X-Forwarded-For $:proxy_add_x_forwarded_for;/proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;/g' $DIR/$DOMAINS.conf
sed -i 's/proxy_set_header X-Real-IP $:remote_addr;/proxy_set_header X-Real-IP $remote_addr;/g' $DIR/$DOMAINS.conf

ln -s $DIR/$DOMAINS.conf $DIR2/$DOMAINS.conf
cat /etc/nginx/sites-available/$DOMAINS.conf
echo "test nginx configure"
nginx -t
echo -e "If nginx is \e[32m OK \e[0m , then you can restart it"
echo -e "Restart Nginx?"
echo "Press enter to continue [y/n]"
read ENTER
if [ $ENTER = "y" ] ;
    then
	echo -e "\e[32m Restart Nginx \e[0m"
	systemctl restart nginx
  check_nginx
	else
	echo "\e[31m Exit \e[0m"
	exit;
fi
